add:exercise-angular-2
SimoPtn/angular pull request #1
Opened 2021-11-03 16:14 UTC by SimoPtn

Completamento esercizio 2 angular

2021-11-04 08:37 UTC, Giulia-Reas requested changes

2021-11-04 08:37 UTC, Giulia-Reas commented on src/app/models/user.ts
> +export interface Companies {
I nomi delle interfacce sono singolari

2021-11-08 11:47 UTC, SimoPtn commented on src/app/models/user.ts
> +export interface Companies {
Ok fatto

2021-11-19 14:21 UTC, Giulia-Reas approved these changes

2021-11-19 14:21 UTC, ghost commented on src/app/models/user.ts
> +export interface Companie {
company e non companie

2021-11-19 14:22 UTC, merged